---
title: "EDS Day 4 - Session A (Leslie Matrix)"
author: "Nicole Pepper"
editor_options: 
  chunk_output_type: console
---

## Create matrices in R

```{r}

# Create a sequence of values ----

my_values <- seq(from = 1, to = 10, by = 1)
my_values

# Convert to matrix ----
my_matrix <- matrix(data = my_values,
                    nrow = 2,
                    ncol = 5,
                    byrow = TRUE)
class(my_matrix)

```

## Incorrectly declared matrix sizes
```{r}
# This warns that the size of the Matrix doesn't fit all of the value range that you gave it
matrix(data = my_values,
       nrow = 2,
       ncol = 3,
       byrow = TRUE)

matrix(data = my_values,
       nrow = 10,
       ncol = 3,
       byrow = TRUE)

```

## Let's do some math with matrices

```{r}
# Scalar multiplication ----
4 * my_matrix

# Create another matrix
my_values2 <- seq(from = 21, to = 30, by = 1)
my_matrix2 <- matrix (data = my_values2,
                      nrow = 2,
                      byrow = TRUE)
my_matrix2

# Add matrices ----
my_matrix + my_matrix2

# Subtract matrices ----
my_matrix - my_matrix2

# Scale/multiple matrices
my_matrix * my_matrix2

# Make a couple 2x2 matrices ----
cats <- matrix(data = c(0, 4, 3, 1),
               nrow = 2, 
               byrow = TRUE)

cats

dogs <- matrix(data = c(6, -3, 0, 2),
               nrow = 2,
               byrow = TRUE)

dogs

# Find the dot product
cats %*% dogs


```

## Leslie matrix model
```{r}

# Create the matrix ----
insect_leslie <- matrix(data = c(0,0,600, 0.2, 0,0 ,0, 0.08, 0),
                        nrow = 3,
                        ncol = 3,
                        byrow = TRUE)

insect_leslie

# Set the initial starting conditions ----
insect_y0 <- c(12000, 700, 500)


# Population at end of year 1 = matrix * initial starting conditions
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# Population at year 2
insect_y2 <- insect_leslie %*% insect_y1
insect_y2

# Population at year 3
insect_y3 <- insect_leslie %*% insect_y2
insect_y3

# Create the matrix for trees
tree_leslie <- matrix(c(0,0,5000, 0.1, 0,0,0,.06,.95),
                      nrow = 3,
                      ncol = 3,
                      byrow = TRUE)
tree_leslie

# Set initial starting conditions
tree_y0 <- c(5000, 0, 0)

# Population at the end of year 1
tree_y1 <- tree_leslie %*% tree_y0

tree_y1

# Population at the end of year 2
tree_y2 <- tree_leslie %*% tree_y1
tree_y2

# Population at the end of year 3
tree_y3 <- tree_leslie %*% tree_y2
tree_y3
```

